version: '3'
services:
  mongo-db:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - fiware
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --host localhost:27017 --username root --password example --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 10
  orion:
    image: fiware/orion:3.7.0
    container_name: orion
    depends_on:
      mongo-db:
        condition: service_healthy
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -dbuser root -dbpwd example
    networks:
      - fiware
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    depends_on:
      - orion
    networks:
      - fiware
  grafana: # NOVO SERVIÇO
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" 
    networks:
      - fiware
    depends_on:
      - orion 

networks:
  fiware:
    driver: bridge