version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - fiware

  orion:
    image: fiware/orion
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: >
      -dbURI mongodb://mongo:27017
      -logLevel INFO
    networks:
      - fiware

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    networks:
      - fiware
    environment:
      - TZ=America/Sao_Paulo

networks:
  fiware:
    driver: bridge
