version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - fiware

  orion:
    image: fiware/orion
    container_name: orion
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: >
      -dbURI mongodb://mongo:27017
      -logLevel INFO
    networks:
      - fiware


networks:
  fiware:
    driver: bridge
